#!/bin/bash

# check that Xcode is installed

if [[ !( -x /usr/bin/gcc && -x /usr/bin/flex && -x /usr/bin/bison ) ]]
then
  echo "You must install the Xcode suite (available from Apple) in order to compile the CWB from source."
  exit
fi
################# !!! TODO - for 3.2.0 and greater, it will also be necessary to check that Glib, PCRE and GNU Readline are available.

# run as root! su or sudo.

who=$(whoami)

if [[ "$who" != root ]]
then
  echo "This script must be run as root."
  echo "Please try again: sudo cwb-install-mac-osx"
  echo "Thanks!"
  exit
fi

cp config.mk config.mk.bak

# set appropriate configuration flags in config.mk (Perl is always available on Mac OS X)

perl -i~ -pe 'if (/^include \$\(TOP\)\/config\/platform\//) { $_ = "include \$(TOP)/config/platform/darwin-core2\n" } elsif (/^include \$\(TOP\)\/config\/site\//) { $_ = "include \$(TOP)/config/site/standard\n" }' config.mk

make clean
make depend
make cl
make utils
make cqp

make install

# restore original state of config file (so subversion doesn't get confused if this is a checked-out version)
rm config.mk
mv config.mk.bak config.mk